--- #YAML:1.0
name:               Shardcache-Client
version:            0.01
abstract:           Client library to access shardcache nodes
author:
    - Andrea Guzzo <xant@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::ConsistentHash::CHash:  0
    Digest::SipHash:      0
    IO::Socket::INET:     0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
